var express = require('express');
var router = express.Router();
var getCollectionConstructor = require('../connectMDB');
const Item = getCollectionConstructor('item');
const Shop = getCollectionConstructor('shop');
const Service = getCollectionConstructor('service');
const Comment = getCollectionConstructor('comment');
const City = getCollectionConstructor('city');

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});
//请求数据的路由

Item.find({},function(err,docs){
    if(!docs.length){
        Item.create([
                {
                    "id":"1001",
                    "title":"云家政",
                    "name":"家庭保洁",
                    "desc":"家庭保洁服务，2小时起订，服务时间未使用完不做退款处理。阿...",
                    "price":35,
                    "oldPrice":45,
                    "orderCount":45341,
                    "soldCount":59583,
                    "commentCount":10312,
                    "accept":"92%",
                    "praise":"86%",
                    "imgUrl":"http://img.daoway.cn/img/price/2017/12/06/47bb440b-5292-4100-8b16-88779f759bf5_thumb.jpg",
                    "company":"上海家谐网络科技有限公司",
                    "profile":"云家政是家政服务在线预订平台。我们的目标是让每个家庭都能获得诚信、便捷、有保障的家政服务。云家政拥有国内最大的实名认证家庭服务员数据库，目前平台上有超过100000名专业服务人员；数百个家政服务商，遍布全国主要城市各个社区。 云家政倡导简单、轻松的生活方式。通过把分散的家政服务能力汇集和分配，让中国家庭获得诚信、便捷、有保障的家政服务，解决日常生活中的麻烦事，把更多时间留给自己和家人，提高生活品质"
                }
            ],function(){});
        Shop.create([
            {
                "serviceIndex":"家庭保洁",
                "serviceType":["小时工","开荒保洁","擦玻璃","深度保洁","杀虫除螨","家居养护"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/03/14/dcbaf0af-d073-480d-8ee7-e39596d82f8f_thumb.jpg",
                        "serviceName":"家庭日常保洁",
                        "description":"计费方式：50元/小时/人服务时长：2小时起 服务范围：...",
                        "price":50
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/12/06/47bb440b-5292-4100-8b16-88779f759bf5_thumb.jpg",
                        "serviceName":"家庭保洁",
                        "description":"家庭保洁服务，2小时起订，服务时间未使用完不做退款处理。阿...",
                        "price":35
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/03/09/8506888a-3514-45df-b3ad-b383fa903591_thumb.jpg",
                        "serviceName":"家庭保洁3小时",
                        "description":"温馨提示：若需要女保洁员请在备注上标明温馨提示：如需多人服...",
                        "price":119
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/11/06/7ba87dd9-dc9c-43cc-aa93-ba0f5f704644_thumb.jpg",
                        "serviceName":"管家式保洁",
                        "description":"服务时长：4小时/人/次；服务时间：根据客户需求定",
                        "price":160
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/07/29/828b41bd-2b21-4127-880b-069ff6cdf0b9_thumb.jpg",
                        "serviceName":"常规家庭保洁(客户自备工具)",
                        "description":"服务内容：家庭保洁服务，2小时起订（本项目需客户自备工具）...",
                        "price":35
                    }

                ]
            },
            {
                "serviceIndex":"上门按摩",
                "serviceType":["中医推拿","油压SPA","局部理疗","足疗套餐","美体塑形","母婴保健"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/08/30/cce534a8-1360-487b-8e18-c404b9b71319_thumb.jpg",
                        "serviceName":"招牌Massage",
                        "description":"90分钟服务姿势：卧姿 适用介绍：适用于工作繁忙...",
                        "price":168
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/11/16/f3abb209-47a6-45d9-9572-84f3bda18c2e_thumb.jpg",
                        "serviceName":"全身推拿调理",
                        "description":"时长:100分钟服务姿势：卧姿适用介绍：头部疼痛、免疫...",
                        "price":268
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/10/12/a3e3d572-faac-4d21-954f-948816fa7c65_thumb.jpg",
                        "serviceName":"初级芳香SPA",
                        "description":"服务时长：70分钟 服务姿势：仰卧 俯卧芳香精油 身心之旅...",
                        "price":298
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/12/10/efe06728-19c0-4e4b-94e1-16c0d778d3a6_thumb.jpg",
                        "serviceName":"生命养护",
                        "description":"时间：90分钟 操作部位：整个中焦 项目介绍：生命养护，人体...",
                        "price":398
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/12/28/7ab8d7c9-5825-4dbd-9ce0-c10b53d52f59_thumb.jpg",
                        "serviceName":"深度油压SPA",
                        "description":"服务时长：90分钟 服务姿势：卧姿 服务人群：适用于精神紧张...",
                        "price":398
                    }
                ]
            },
            {
                "serviceIndex":"上门维修",
                "serviceType":["手机维修","家电维修","电脑维修","家庭维修","管道疏通","开锁换锁","安装打孔","装修换新","空气净化"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/12/06/20851d75-b5c8-41bd-92cb-7937eeed7d89_thumb.jpg",
                        "serviceName":"空调维修",
                        "description":"1元上门费可抵扣30元维修费此项目价格仅为上门检测费 服务...",
                        "price":1
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/11/01/dc366a20-f972-4a0b-97a1-393ff80755ea_thumb.jpg",
                        "serviceName":"专业疏通马桶",
                        "description":"1、手电动疏通 解决马桶地漏堵塞等问题。 2、此项目不包含拆...",
                        "price":100
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2018/02/01/16dd78e6-4fbb-4810-b941-e68060b6baa7_thumb.jpg",
                        "serviceName":"疏通下水道",
                        "description":"对于因建筑垃圾、抹布、掉东西！有专业的手段！1:此价格是普...",
                        "price":100
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2015/08/20/07ecb6ad-1b70-46e4-87ab-42e2d09cd30f_thumb.jpg",
                        "serviceName":"笔记本上门维修项目",
                        "description":"故障描述：专业维修笔记本开机黑屏，开机蓝屏死机，开机花屏，...",
                        "price":45
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/12/30/b40ab8f5-4d94-465d-8311-a8270c4d2f59_thumb.jpg",
                        "serviceName":"水路管件漏水维修，各种水管检修",
                        "description":"依据房屋结构走管，包含水管，不含阀门，清运垃圾，一站式上门服...",
                        "price":89
                    }
                ]
            },
            {
                "serviceIndex":"家电清洗",
                "serviceType":["油烟机清洗","洗衣机清洗","空调清洗","冰箱清洗","燃气灶清洗","热水器清洗","微波炉清洗","饮水机清洗","消毒柜清洗"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/02/24/de8efc1b-c521-45a8-871f-6514a4e443a0_thumb.jpg",
                        "serviceName":"中式油烟机清洗（免拆洗）",
                        "description":"1、服务内容：使用专业工具和清洗剂，对油烟机外壳、内壁、油...",
                        "price":140
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/06/12/1468d89d-df46-4a0a-8f31-77aa6d5854b7_thumb.jpg",
                        "serviceName":"中欧式油烟机清洗",
                        "description":"服务流程：1.工具准备（防护罩 折叠桶 螺丝刀 家电蒸汽清...",
                        "price":120
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/05/26/3d45e80c-71e5-45b5-8ee7-1db9a0280523_thumb.jpg",
                        "serviceName":"油烟机拆机洗",
                        "description":"我们是TCL集团旗下家电服务品牌 服务流程：1.验机 2....",
                        "price":208
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/09/14/96826989-a579-4093-b3a5-54949d25bc24_thumb.jpg",
                        "serviceName":"抽油烟机现场清洗",
                        "description":"服务流程:1.验机，2.拍照，做家庭防护，准备工具，3...",
                        "price":158
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/07/16/3996095c-2145-4aa3-b995-da3143532893_thumb.jpg",
                        "serviceName":"1台挂机+1台柜机深度清洗",
                        "description":"服务流程：1.验机 2.准备工具、做家庭防护 3.专用清洗...",
                        "price":270
                    }
                ]
            },
            {
                "serviceIndex":"衣物洗护",
                "serviceType":["洗衣","洗鞋修鞋","家纺清洗","箱包洗护","定制改衣"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/09/05/ff7f8614-074e-43b0-910a-6d865f22f855_thumb.jpg",
                        "serviceName":"冬装精洗护理套餐",
                        "description":"服务内容：1.本商品可清洗冬装类衣物2件，包括：羽绒服、毛...",
                        "price":45
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/12/19/915d51ad-a07f-476a-aec4-fcfdb88a33f3_thumb.jpg",
                        "serviceName":"4双不限鞋类无忧洗",
                        "description":"服务内容：1次四双鞋子不限种类精洗，不包含修补、翻新服务，...",
                        "price":89
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/01/04/8de1426a-163c-4398-80fd-a892198e0fe8_thumb.jpg",
                        "serviceName":"棉衣/羽绒服（短款）",
                        "description":"服务内容：短款棉衣/羽绒服（衣物长度未超过臀部，视为短款。...",
                        "price":40
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/03/01/edd4ab2b-65c0-46ee-8d88-fe13c8c59dc3_thumb.jpg",
                        "serviceName":"3双不限鞋类畅快洗",
                        "description":"服务内容：1次三双鞋子不限种类精洗，不包含修补、翻新服务，...",
                        "price":69
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/12/28/28a4d43d-3c16-4388-9188-dc2855b331a7_thumb.jpg",
                        "serviceName":"棉衣/羽绒服（长款）",
                        "description":"服务内容：长款棉衣/羽绒服（衣物长度未超过臀部，视为短款。...",
                        "price":50
                    }
                ]
            },
            {
                "serviceIndex":"搬家速运",
                "serviceType":["搬家租车","一站式搬家","货运的士","拆装搬运","仓储寄存"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/11/07/55d0dd28-35e1-4f22-bc51-543f385044d0_thumb.jpg",
                        "serviceName":"金杯车搬家",
                        "description":"服务内容：1.金杯车辆容积：28个24寸行李箱大小，可装载...",
                        "price":166
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/11/07/832382ec-51e2-42a8-90f3-3ef86ab75a1c_thumb.jpg",
                        "serviceName":"厢货搬家",
                        "description":"服务内容：1.车厢长4.2m、宽1.9、高1.9 2.此目...",
                        "price":348
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/09/13/8505580f-d1b9-48e3-924b-527a7891374d_thumb.jpg",
                        "serviceName":"普通居民搬家",
                        "description":"1.车型:厢货4.2M*2M*1.9M 2.里程：此项目起步...",
                        "price":280
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/11/24/c8f9037c-8deb-4848-8713-11d8f981e43d_thumb.jpg",
                        "serviceName":"面包车拉货",
                        "description":"服务内容：【车辆容积】12个24寸行李箱大小，可装载个人物...",
                        "price":35
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/08/16/5ae86d7c-6aba-4090-93ef-1a1762a78609_thumb.jpg",
                        "serviceName":"搬运小时工服务",
                        "description":"1.最低两人，最低俩小时，一人一小时100元 2.此项目适合...",
                        "price":100
                    }
                ]
            },
            {
                "serviceIndex":"美容美妆",
                "serviceType":["美容","美甲","美睫","化妆","美发","半永久"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/02/01/2c2ce1bb-c041-4b3c-95a4-121ce38aa56b_thumb.jpg",
                        "serviceName":"面部补水+面部拨筋+眼部拨筋",
                        "description":"服务时长：90分钟 服务姿势：躺姿 服务部位：面部 服务流程...",
                        "price":298
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/01/21/79d5c372-fde0-4e0e-8fed-5e1b6fbd7642_thumb.jpg",
                        "serviceName":"欧式性感美睫微密电眼款",
                        "description":"服务内容；美睫造型双眼130根操作流程；技师手部消毒—眼部...",
                        "price":328
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/09/27/1594e212-2cc9-4bea-a18b-14b08676f78a_thumb.jpg",
                        "serviceName":"自然型睫毛",
                        "description":"韩国进口空心睫毛，特点：耐高温，不易变形、眼感舒适。可以根据...",
                        "price":238
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/12/14/a250e83a-e0a5-465b-a2bd-186d9c009b74_thumb.jpg",
                        "serviceName":"下睫毛美睫",
                        "description":"下睫毛嫁接 此款睫毛的长度、弧度、会根据您的眼型设计一款属于..",
                        "price":198
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/03/16/16788863-f293-48c7-adfb-50192e22eb4b_thumb.jpg",
                        "serviceName":"剪发=宝宝剪发",
                        "description":"宝宝剪发，宝宝理发，宝宝剃胎毛，满月剃发，百天剃发。福意☞要..",
                        "price":128
                    }
                ]
            },
            {
                "serviceIndex":"上门医护",
                "serviceType":["护士上门","挂号陪诊","康复陪护","上门体检"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/04/18/bd3504fb-6c13-41f1-8fac-d963ab85db5e_thumb.jpg",
                        "serviceName":"天天护（重症）",
                        "description":"服务简介：满足医院或者居家的短期护理需求，主要包括住院期护...",
                        "price":220
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/02/02/23861d73-0c3b-4c2e-9a7c-d307cf6502a1_thumb.jpg",
                        "serviceName":"灌肠护理服务项目",
                        "description":"一、服务介绍：灌肠法是用导管自肛门经直肠插入结肠灌注液体，...",
                        "price":268
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/01/29/67ac5e04-d589-441d-a9db-c19fc45c3de7_thumb.jpg",
                        "serviceName":"鼻饲/留置胃管 执业护士上门",
                        "description":"执业护士上门鼻饲/留置胃管服务（169元/单次），预约时间请...",
                        "price":169
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/07/11/bbdb92dc-b487-4627-bdd0-55dee5f165e1_thumb.jpg",
                        "serviceName":"护士上门拆线",
                        "description":"医院在职护士提供上门拆线条服务（260元/次），预约服务时请...",
                        "price":260
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2018/02/02/bf1925de-f679-4ee4-a2eb-16476185a41b_thumb.jpg",
                        "serviceName":"上门输液（高级）全程看护",
                        "description":"一、服务介绍：上门输液服务，是由专业的护士上门，为需要进行...",
                        "price":298
                    }
                ]
            },
            {
                "serviceIndex":"保姆月嫂",
                "serviceType":["家务保姆","月嫂","育儿嫂","做饭阿姨","老人陪护"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/04/01/bac42d83-e4aa-458c-a4ac-eb09ecbe4a6e_thumb.jpg",
                        "serviceName":"住家保姆",
                        "description":"服务内容：家务、洗衣、做饭、照顾老人、病人护理、接送孩子，...",
                        "price":3500
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/11/15/7ce78385-769d-4661-95e3-2f4bc2adb5ec_thumb.jpg",
                        "serviceName":"老人陪护",
                        "description":"服务内容：做饭 保洁 陪伴沟通 居室整理 注：1.佣金为...",
                        "price":4000
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/08/28/d401cd0b-d89f-4bbf-be9d-5c9d632b8811_thumb.jpg",
                        "serviceName":"月嫂",
                        "description":"1.服务时间为26天，服务期间不满意，随时调整换人。2.免...",
                        "price":6800
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/04/01/e56397a4-ac2b-4ff8-843d-00ed0bca2de2_thumb.jpg",
                        "serviceName":"育儿嫂",
                        "description":"婴幼儿生活护理、常见病护理、潜能开房、专业护理，习惯培养、互...",
                        "price":5500
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/11/15/168fcc5e-69cd-4652-af06-7faf66754013_thumb.jpg",
                        "serviceName":"住家育儿嫂",
                        "description":"服务内容（根据级别归类服务内容）1.宝宝喂养—母乳喂养、辅...",
                        "price":5000
                    }
                ]
            },
            {
                "serviceIndex":"养车用车",
                "serviceType":["上门养车","上门洗车","汽车陪练","车务代办","机场泊车"],
                "shopList":[
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/12/22/71a7a1c1-2d88-4834-877e-3d630d611c15_thumb.jpg",
                        "serviceName":"首单体验陪练158元2小时",
                        "description":"活动规则：1. 本活动只限新用户首单、首次体验，只限体验一...",
                        "price":79
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2017/04/19/c358bd9f-2e52-4537-86b4-c356276a3515_thumb.jpg",
                        "serviceName":"上门洗车（标准洗）",
                        "description":"服务时间：30分钟 服务内容：清洗全车漆面，玻璃，轮毂，轮...",
                        "price":59
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/12/06/e4e6056e-4a4c-4adf-9543-6a55f93380b3_thumb.jpg",
                        "serviceName":"内饰深度清洁翻新+洗车",
                        "description":"服务项目 1.清洗车辆外表 2.仪表台塑料件护理 3.中控台...",
                        "price":328
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/2016/07/06/cd8be51d-4b4e-4713-bb0b-73508dc37c06_thumb.jpg",
                        "serviceName":"大保养+全车检测",
                        "description":"费用说明：1.安耐驰全合成SN5w40机油4L+品牌机滤+...",
                        "price":398
                    },
                    {
                        "imgUrl":"http://img.daoway.cn/img/price/2017/07/24/0f5d9751-7453-4046-8b53-a5310aba44b6_thumb.jpg",
                        "serviceName":"上门发动机舱精洗",
                        "description":"精洗发动机舱表面重污，养护元件及和线束；防止线路老化，保护发..",
                        "price":128
                    }
                ]
            }
        ],function(){});
        Service.create([
            {
                "id":"1001",
                "title":"云家政",
                "orderCount":45186,
                "positiveRate":"86%",
                "imgUrl":"http://img.daoway.cn/img/2016/12/28/5cf8680f-0264-4686-ba05-145700db6063_thumb.jpg"
            },
            {
                "id":"1002",
                "title":"宜生到家",
                "orderCount":17799,
                "positiveRate":"98%",
                "imgUrl":"http://img.daoway.cn/img/2017/01/20/c3a2490e-04fc-43de-9a05-8a62dce47f57_thumb.jpg"
            },
            {
                "id":"1003",
                "title":"优洗汇",
                "orderCount":762,
                "positiveRate":"84%",
                "imgUrl":"http://img.daoway.cn/img/2017/06/07/6e3e55b7-7158-48bf-bf38-25ae823a8fce_thumb.jpg"
            },
            {
                "id":"1004",
                "title":"三鼎家政",
                "orderCount":26545,
                "positiveRate":"84%",
                "imgUrl":"http://img.daoway.cn/img/2016/08/24/fbc97e65-6f09-4244-bfd5-91ed25e529a9_thumb.jpg"
            },
            {
                "id":"1005",
                "title":"Hi维修",
                "orderCount":1861,
                "positiveRate":"97%",
                "imgUrl":"http://img.daoway.cn/img/2017/07/14/cab26b89-7b5b-4ddb-81cf-ff14de30d424_thumb.jpg"
            },
            {
                "id":"1006",
                "title":"轻松到家",
                "orderCount":1034,
                "positiveRate":"93%",
                "imgUrl":"http://img.daoway.cn/img/2017/10/09/49bf0366-586c-4071-bee8-b65e90e06990_thumb.jpg"
            },
            {
                "id":"1007",
                "title":"你点到家",
                "orderCount":1956,
                "positiveRate":"100%",
                "imgUrl":"http://img.daoway.cn/img/2017/08/07/8c228c28-2707-47ef-93fb-5643f2e883e9_thumb.jpg"
            },
            {
                "id":"1008",
                "title":"十分到家",
                "orderCount":5219,
                "positiveRate":"96%",
                "imgUrl":"http://img.daoway.cn/img/2017/10/17/51931b93-0f2a-468f-9a92-a87c36c9c9f1_thumb.jpg"
            },
            {
                "id":"1009",
                "title":"明蕊丽人",
                "orderCount":1185,
                "positiveRate":"98%",
                "imgUrl":"http://img.daoway.cn/img/2017/08/08/1b856de8-ed4b-4d3c-91dd-c7d3b4f12b12_thumb.jpg"
            },
            {
                "id":"1010",
                "title":"大众工匠",
                "orderCount":435,
                "positiveRate":"99%",
                "imgUrl":"http://img.daoway.cn/img/2018/01/16/d0f95f9a-2e9f-4b37-ab2c-2dfb6c66f2b8_thumb.jpg"
            },
            {
                "id":"1011",
                "title":"魔魔达",
                "orderCount":4040,
                "positiveRate":"99%",
                "imgUrl":"http://img.daoway.cn/img/2016/02/19/21762b1d-08e9-4dd8-847a-baee2b3b94a3_thumb.jpg"
            },
            {
                "id":"1012",
                "title":"闪修侠",
                "orderCount":933,
                "positiveRate":"97%",
                "imgUrl":"http://img.daoway.cn/img/2015/09/15/e8419c3c-a302-484c-a0c2-67fc7b87e77d_thumb.jpg"
            },
            {
                "id":"1013",
                "title":"哈喽维修",
                "orderCount":260,
                "positiveRate":"97%",
                "imgUrl":"http://img.daoway.cn/img/2016/06/21/6441ca7d-cd34-4474-870d-2ee9180232f6_thumb.jpg"
            },
            {
                "id":"1014",
                "title":"美着呢",
                "orderCount":333,
                "positiveRate":"94%",
                "imgUrl":"http://img.daoway.cn/img/2016/11/08/e874effd-75d5-408a-84a9-73bfe135b666_thumb.jpg"
            },
            {
                "id":"1015",
                "title":"理大师",
                "orderCount":1353,
                "positiveRate":"97%",
                "imgUrl":"http://img.daoway.cn/img/2016/01/26/07744489-e94e-41ef-a971-5d01a0db7b8b_thumb.jpg"
            },
            {
                "id":"1016",
                "title":"e修鸽",
                "orderCount":2473,
                "positiveRate":"93%",
                "imgUrl":"http://img.daoway.cn/img/2015/12/28/d53343ce-5818-4ebf-9948-d13aa100ef72_thumb.jpg"
            },
            {
                "id":"1017",
                "title":"e修时代手机维修",
                "orderCount":197,
                "positiveRate":"98%",
                "imgUrl":"http://img.daoway.cn/img/2016/03/14/b7599447-d389-4c32-b4b6-4811cbce4c27_thumb.jpg"
            },
            {
                "id":"1018",
                "title":"甲马洗车",
                "orderCount":575,
                "positiveRate":"97%",
                "imgUrl":"http://img.daoway.cn/img/2017/04/19/da0d7242-d351-4d27-9a0a-01e6132bdac1_thumb.jpg"
            },
            {
                "id":"1019",
                "title":"医护到家",
                "orderCount":259,
                "positiveRate":"97%",
                "imgUrl":"http://img.daoway.cn/img/2016/08/12/faa7757b-0c49-4a42-8b18-086ffdd4dea1_thumb.jpg"
            },
            {
                "id":"1020",
                "title":"蓝犀牛货运",
                "orderCount":111,
                "positiveRate":"95%",
                "imgUrl":"http://img.daoway.cn/img/2017/11/24/d075155c-78d4-41e3-8bec-618c5f80c2ff_thumb.jpg"
            },
            {
                "id":"1021",
                "title":"精诚电脑维修",
                "orderCount":1339,
                "positiveRate":"98%",
                "imgUrl":"http://img.daoway.cn/img/2017/02/28/ce9dd147-e069-4699-87ee-a2e2a300247b_thumb.jpg"
            },
            {
                "id":"1022",
                "title":"彦仕阁健康理疗",
                "orderCount":5100,
                "positiveRate":"99%",
                "imgUrl":"http://img.daoway.cn/img/2016/10/12/95f4a9fc-04ae-431f-b42b-2608e4915db2_thumb.jpg"
            },
            {
                "id":"1023",
                "title":"卡拉丁汽车服务",
                "orderCount":15,
                "positiveRate":"100%",
                "imgUrl":"http://img.daoway.cn/img/2017/07/25/e2019903-8655-45a0-9dd0-47844b953fd2_thumb.jpg"
            },
            {
                "id":"1024",
                "title":"极吼吼",
                "orderCount":489,
                "positiveRate":"95%",
                "imgUrl":"http://img.daoway.cn/img/2017/07/14/0a2b606a-fdf4-4e79-a1b3-b254dfe5f731_thumb.jpg"
            }
        ],function(){});
        Comment.create([
            {
                "iconUrl":"http://img.daoway.cn/img/2017/12/30/adf81789-db5b-47d6-a0fb-efbdadc95b54.jpg",
                "area":"普陀区",
                "city":"上海",
                "comment":"阿姨服务非常好，收拾的很干净。",
                "createtime":1521196598000,
                "nick":"啦啦6666",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/ajNVdqHZLLC5fgciaiaRwm8N48jQG3UahS0Cl34okmQZDcJPGicDYPmoicetPWxPx07clPyFicMEEqYicJkib2LzLEBnQ/0",
                "area":"徐汇区",
                "city":"上海",
                "comment":"准时到达，态度热情，阿姨态度是好的，但是打扫的没有很认真，很多小地方还是挺脏的，阿姨打扫完自己又接着打扫了很久。。",
                "createtime":1521192005000,
                "nick":"阿***",
                "star":3
            },
            {
                "iconUrl":"https://thirdqq.qlogo.cn/qqapp/1103839060/A6F7F782649485AF535B9E4B545127E6/100",
                "area":"浦东新区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521186979000,
                "nick":"yang98792",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/sXkDNHriahEeqD8cicickXHWl0pO1JXcn8YGQuCt5cMCkAia7JSgXnQRxW03bGJ1T8VvYD21LgIVZzPeIkKYDUqpDA/0",
                "area":"杨浦区",
                "city":"上海",
                "comment":"准时到达",
                "createtime":1521182381000,
                "nick":"天之骄子小丽丽",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/11/26/73d69784-4d04-431a-92d9-a8bd21e29518.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521180074000,
                "nick":"邵小笑。",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/GtS5XXtiaCDaXZX34gjkBB3wvEIH8iaH4Queicyw9lOVzgZcxmKqugUyJWgicuPCR9Uicw8ZNdjicSP0nFic2FLDLFreocxHZtlToKO/0",
                "area":"虹口区",
                "city":"上海",
                "comment":"态度热情，服务专业",
                "createtime":1521177079000,
                "nick":"Eli5",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"浦东新区",
                "city":"上海",
                "comment":"服务专业，态度热情，准时到达",
                "createtime":1521175494000,
                "nick":"薛伟明",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"西城区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，阿姨打扫得非常干净整洁 帮了我的大忙 万分感谢",
                "createtime":1521175171000,
                "nick":"清朗的世界",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，值得关注的商家",
                "createtime":1521171938000,
                "nick":"u16046831",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJll76R1TnjSrAZRpJ4OzRDlwYs3VRd6wCDq3miczEqZebHJEqMa9xNnRLA1shJXZaoBDmDUtaMaTg/0",
                "area":"浦东新区",
                "city":"上海",
                "comment":"不太认真 拖时间",
                "createtime":1521171160000,
                "nick":"Ashley徐蕾",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/12/13/f8abe707-61df-4032-99fd-99f1da0a25df.jpg",
                "area":"徐汇区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521118095000,
                "nick":"u29562927",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/11/30/9145df02-6c46-4e85-83f6-ccb0c37742f7.jpg",
                "area":"浦东新区",
                "city":"上海",
                "comment":"阿姨态度蛮好，迟到了直说对不起，清洁能力确不咋滴，房间搞了很久，弄到最后客厅马马虎虎的打扫，本来不会评论，但今天意外发现，房间主卧的床下因让她打扫床后给她移动过，地板有磨坏的痕迹，真心郁闷，不得不差评",
                "createtime":1521109205000,
                "nick":"u78690105",
                "star":2
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/oqjmvaMlmyfibgPboLbbdcPVYOE29GPzsJNUYEzLmXXqUgibT6H8TnK3hnialpaqz7zDHnhclKxBXXR6aMic21cbtkTjQdBdmrPd/0",
                "area":"西城区",
                "city":"北京",
                "comment":"服务专业，态度热情，准时到达",
                "createtime":1521107597000,
                "nick":"Hh26",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83erYUwe91zYWvX3BicZoEn41IJBBqSMMZ8csgial5lKA6za1LeTeBnrfXDgfkthPVop0NQu4Qkfoa3icw/132",
                "area":"黄浦区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521107165000,
                "nick":"〰20",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmiaNPYbLOk7NBQxdUPDgGaiagxCBDKF26zjibIs2ia1lD2T7cEOzPL8NQBZMCIcDFpus7ia7wSu3vArQ/132",
                "area":"罗湖区",
                "city":"深圳",
                "comment":"嗯呢 服务很好",
                "createtime":1521102876000,
                "nick":"Marco Zambaldo",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/hqDXUD6csUibTwZibQosRbiagoNofUCRXrib28NQribGibyITJ470E2IHnPvkROiaMWCT7lqHryrJnmgMgTqXaqAxzqtw/0",
                "area":"丰台区",
                "city":"北京",
                "comment":"服务太差劲，之前叫了几次保洁阿姨都很好干净，今天这个太差太差，垃圾也不带帮忙带下去",
                "createtime":1521102420000,
                "nick":"u72955327",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/PCyiaLnicfRyDtgeymjP0tovB6ocuGbSens6DoUTHtsRFhjwl19uEWIBDWX9F7MWx6sxldDFMNzcGXktY95glcpw/132",
                "area":"东城区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，很棒",
                "createtime":1521101462000,
                "nick":"呵呵碰",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2018/03/14/2271c471-dea3-437f-a937-00f3a181af42.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521093966000,
                "nick":"HISA-排骨君",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83ep4NILvBubLqyiaIpHHjeicoTczBk5JcqsngAkMGTtahwnFiaLeR1e8o3asmGNCD7rVzIN5GCzNtUCaA/0",
                "area":"昌平区",
                "city":"北京",
                "comment":"客服很好",
                "createtime":1521093140000,
                "nick":"大菲1",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83eqKEnl7B1sLKbVCc0BTNRIZDKkFtwibf8flM2zaE6NfBmMQNy9DeoGjquXibBFcJ71MAckHLeC2m6rQ/0",
                "area":"顺义区",
                "city":"北京",
                "comment":"云家证动不动就取消订单，打乱时间计划",
                "createtime":1521085158000,
                "nick":"静***",
                "star":3
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/ajNVdqHZLLAgfsiavqfFLibxRs6OGYG6d4LpjYcsj3TpCE8TGwUiajbPDkB7WTRCtibBqYnKd8jpwX11aTK6AI9MWg/0",
                "area":"卢湾区",
                "city":"上海",
                "comment":"态度热情，准时到达，服务专业",
                "createtime":1520909483000,
                "nick":"-.-10",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/Q5xPxqRgZicXHJFFA0cvdyUeuwndkF4khrBazP3EunLpvp2bNGlUwKhLiaYox84Q9B1HIBVLv8xpHRufQ7ibDbfZwCEjHcrdwJq/0",
                "area":"南山区",
                "city":"深圳",
                "comment":"态度热情，服务专业，准时到达",
                "createtime":1520908242000,
                "nick":"王信1",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/PwsCl8vJ2Ubg9GWmTCjlAjxuWMo2hylyUvm0LGPvNhFuu3kI5XXpDNjtFJsqjic00tt1vTneiayESqwBCUr6pp4w/132",
                "area":"罗湖区",
                "city":"深圳",
                "comment":"准时到达，打扫的一般，已经做了心理准备，在预期接受范围内。就是浪费水浪费的太严重了，中国那么多地方缺水，更别提全球了。希望公司和员工提倡下节约用水！！！",
                "createtime":1520860484000,
                "nick":"A***",
                "star":4
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/wIzdjxOSE0b56dc9ibXLPNJOJtZAxncPb3PxaEtj51KtsbxKdvZjePdB2d2XJ1aU9uDSFvOJbN71BbCvveia1Hog/132",
                "area":"朝阳",
                "city":"北京",
                "comment":"话多，还弄得不干净",
                "createtime":1520860281000,
                "nick":"排***",
                "star":3
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/Q5xPxqRgZicXHJFFA0cvdyUeuwndkF4khrBazP3EunLpvp2bNGlUwKhLiaYox84Q9B1HIBVLv8xpHRufQ7ibDbfZwCEjHcrdwJq/0",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520857879000,
                "nick":"理合",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2016/08/03/8c970507-66c2-4a81-93bc-a32c2746509e.jpg",
                "area":"海淀区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，特别好",
                "createtime":1520851926000,
                "nick":"李丹蕾",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/uwm9pVB4gDlKibGbRCbN4v2PnnY9guSnJxJaHZ4dicTK5JQMG2EfvLJ0HYgZLrHp7nFLXXNYZCdSEQSbVmGGnSyA/0",
                "area":"荔湾区",
                "city":"广州",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520844348000,
                "nick":"小芝麻2",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/z7Nba05uObuZ10tmT2gksxWR7zMeBERBo3HAjtnwGQV8X6mcc9w2ibXy4Jgs3Vjh7m3sAibAHxicHlghhJjiaOXftw/132",
                "area":"南山区",
                "city":"深圳",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520837432000,
                "nick":"理合",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2016/09/10/9b720bbd-b001-453d-b73b-86d6fb187d7d.jpg",
                "area":"武侯区",
                "city":"成都",
                "comment":"态度热情",
                "createtime":1520831084000,
                "nick":"唐wl",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2018/03/11/3c159dc9-c4ec-40d7-9144-9fc90f480a16.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，很好的",
                "createtime":1520830596000,
                "nick":"u16046831",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/12/30/adf81789-db5b-47d6-a0fb-efbdadc95b54.jpg",
                "area":"普陀区",
                "city":"上海",
                "comment":"阿姨服务非常好，收拾的很干净。",
                "createtime":1521196598000,
                "nick":"啦啦6666",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/ajNVdqHZLLC5fgciaiaRwm8N48jQG3UahS0Cl34okmQZDcJPGicDYPmoicetPWxPx07clPyFicMEEqYicJkib2LzLEBnQ/0",
                "area":"徐汇区",
                "city":"上海",
                "comment":"准时到达，态度热情，阿姨态度是好的，但是打扫的没有很认真，很多小地方还是挺脏的，阿姨打扫完自己又接着打扫了很久。。",
                "createtime":1521192005000,
                "nick":"阿***",
                "star":3
            },
            {
                "iconUrl":"https://thirdqq.qlogo.cn/qqapp/1103839060/A6F7F782649485AF535B9E4B545127E6/100",
                "area":"浦东新区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521186979000,
                "nick":"yang98792",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/sXkDNHriahEeqD8cicickXHWl0pO1JXcn8YGQuCt5cMCkAia7JSgXnQRxW03bGJ1T8VvYD21LgIVZzPeIkKYDUqpDA/0",
                "area":"杨浦区",
                "city":"上海",
                "comment":"准时到达",
                "createtime":1521182381000,
                "nick":"天之骄子小丽丽",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/11/26/73d69784-4d04-431a-92d9-a8bd21e29518.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521180074000,
                "nick":"邵小笑。",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/GtS5XXtiaCDaXZX34gjkBB3wvEIH8iaH4Queicyw9lOVzgZcxmKqugUyJWgicuPCR9Uicw8ZNdjicSP0nFic2FLDLFreocxHZtlToKO/0",
                "area":"虹口区",
                "city":"上海",
                "comment":"态度热情，服务专业",
                "createtime":1521177079000,
                "nick":"Eli5",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"浦东新区",
                "city":"上海",
                "comment":"服务专业，态度热情，准时到达",
                "createtime":1521175494000,
                "nick":"薛伟明",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"西城区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，阿姨打扫得非常干净整洁 帮了我的大忙 万分感谢",
                "createtime":1521175171000,
                "nick":"清朗的世界",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，值得关注的商家",
                "createtime":1521171938000,
                "nick":"u16046831",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJll76R1TnjSrAZRpJ4OzRDlwYs3VRd6wCDq3miczEqZebHJEqMa9xNnRLA1shJXZaoBDmDUtaMaTg/0",
                "area":"浦东新区",
                "city":"上海",
                "comment":"不太认真 拖时间",
                "createtime":1521171160000,
                "nick":"Ashley徐蕾",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/12/13/f8abe707-61df-4032-99fd-99f1da0a25df.jpg",
                "area":"徐汇区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521118095000,
                "nick":"u29562927",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/11/30/9145df02-6c46-4e85-83f6-ccb0c37742f7.jpg",
                "area":"浦东新区",
                "city":"上海",
                "comment":"阿姨态度蛮好，迟到了直说对不起，清洁能力确不咋滴，房间搞了很久，弄到最后客厅马马虎虎的打扫，本来不会评论，但今天意外发现，房间主卧的床下因让她打扫床后给她移动过，地板有磨坏的痕迹，真心郁闷，不得不差评",
                "createtime":1521109205000,
                "nick":"u78690105",
                "star":2
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/oqjmvaMlmyfibgPboLbbdcPVYOE29GPzsJNUYEzLmXXqUgibT6H8TnK3hnialpaqz7zDHnhclKxBXXR6aMic21cbtkTjQdBdmrPd/0",
                "area":"西城区",
                "city":"北京",
                "comment":"服务专业，态度热情，准时到达",
                "createtime":1521107597000,
                "nick":"Hh26",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83erYUwe91zYWvX3BicZoEn41IJBBqSMMZ8csgial5lKA6za1LeTeBnrfXDgfkthPVop0NQu4Qkfoa3icw/132",
                "area":"黄浦区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521107165000,
                "nick":"〰20",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmiaNPYbLOk7NBQxdUPDgGaiagxCBDKF26zjibIs2ia1lD2T7cEOzPL8NQBZMCIcDFpus7ia7wSu3vArQ/132",
                "area":"罗湖区",
                "city":"深圳",
                "comment":"嗯呢 服务很好",
                "createtime":1521102876000,
                "nick":"Marco Zambaldo",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/hqDXUD6csUibTwZibQosRbiagoNofUCRXrib28NQribGibyITJ470E2IHnPvkROiaMWCT7lqHryrJnmgMgTqXaqAxzqtw/0",
                "area":"丰台区",
                "city":"北京",
                "comment":"服务太差劲，之前叫了几次保洁阿姨都很好干净，今天这个太差太差，垃圾也不带帮忙带下去",
                "createtime":1521102420000,
                "nick":"u72955327",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/PCyiaLnicfRyDtgeymjP0tovB6ocuGbSens6DoUTHtsRFhjwl19uEWIBDWX9F7MWx6sxldDFMNzcGXktY95glcpw/132",
                "area":"东城区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，很棒",
                "createtime":1521101462000,
                "nick":"呵呵碰",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2018/03/14/2271c471-dea3-437f-a937-00f3a181af42.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521093966000,
                "nick":"HISA-排骨君",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83ep4NILvBubLqyiaIpHHjeicoTczBk5JcqsngAkMGTtahwnFiaLeR1e8o3asmGNCD7rVzIN5GCzNtUCaA/0",
                "area":"昌平区",
                "city":"北京",
                "comment":"客服很好",
                "createtime":1521093140000,
                "nick":"大菲1",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83eqKEnl7B1sLKbVCc0BTNRIZDKkFtwibf8flM2zaE6NfBmMQNy9DeoGjquXibBFcJ71MAckHLeC2m6rQ/0",
                "area":"顺义区",
                "city":"北京",
                "comment":"云家证动不动就取消订单，打乱时间计划",
                "createtime":1521085158000,
                "nick":"静***",
                "star":3
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/ajNVdqHZLLAgfsiavqfFLibxRs6OGYG6d4LpjYcsj3TpCE8TGwUiajbPDkB7WTRCtibBqYnKd8jpwX11aTK6AI9MWg/0",
                "area":"卢湾区",
                "city":"上海",
                "comment":"态度热情，准时到达，服务专业",
                "createtime":1520909483000,
                "nick":"-.-10",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/Q5xPxqRgZicXHJFFA0cvdyUeuwndkF4khrBazP3EunLpvp2bNGlUwKhLiaYox84Q9B1HIBVLv8xpHRufQ7ibDbfZwCEjHcrdwJq/0",
                "area":"南山区",
                "city":"深圳",
                "comment":"态度热情，服务专业，准时到达",
                "createtime":1520908242000,
                "nick":"王信1",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/PwsCl8vJ2Ubg9GWmTCjlAjxuWMo2hylyUvm0LGPvNhFuu3kI5XXpDNjtFJsqjic00tt1vTneiayESqwBCUr6pp4w/132",
                "area":"罗湖区",
                "city":"深圳",
                "comment":"准时到达，打扫的一般，已经做了心理准备，在预期接受范围内。就是浪费水浪费的太严重了，中国那么多地方缺水，更别提全球了。希望公司和员工提倡下节约用水！！！",
                "createtime":1520860484000,
                "nick":"A***",
                "star":4
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/wIzdjxOSE0b56dc9ibXLPNJOJtZAxncPb3PxaEtj51KtsbxKdvZjePdB2d2XJ1aU9uDSFvOJbN71BbCvveia1Hog/132",
                "area":"朝阳",
                "city":"北京",
                "comment":"话多，还弄得不干净",
                "createtime":1520860281000,
                "nick":"排***",
                "star":3
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/Q5xPxqRgZicXHJFFA0cvdyUeuwndkF4khrBazP3EunLpvp2bNGlUwKhLiaYox84Q9B1HIBVLv8xpHRufQ7ibDbfZwCEjHcrdwJq/0",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520857879000,
                "nick":"理合",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2016/08/03/8c970507-66c2-4a81-93bc-a32c2746509e.jpg",
                "area":"海淀区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，特别好",
                "createtime":1520851926000,
                "nick":"李丹蕾",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/uwm9pVB4gDlKibGbRCbN4v2PnnY9guSnJxJaHZ4dicTK5JQMG2EfvLJ0HYgZLrHp7nFLXXNYZCdSEQSbVmGGnSyA/0",
                "area":"荔湾区",
                "city":"广州",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520844348000,
                "nick":"小芝麻2",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/z7Nba05uObuZ10tmT2gksxWR7zMeBERBo3HAjtnwGQV8X6mcc9w2ibXy4Jgs3Vjh7m3sAibAHxicHlghhJjiaOXftw/132",
                "area":"南山区",
                "city":"深圳",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520837432000,
                "nick":"理合",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2016/09/10/9b720bbd-b001-453d-b73b-86d6fb187d7d.jpg",
                "area":"武侯区",
                "city":"成都",
                "comment":"态度热情",
                "createtime":1520831084000,
                "nick":"唐wl",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2018/03/11/3c159dc9-c4ec-40d7-9144-9fc90f480a16.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，很好的",
                "createtime":1520830596000,
                "nick":"u16046831",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/12/30/adf81789-db5b-47d6-a0fb-efbdadc95b54.jpg",
                "area":"普陀区",
                "city":"上海",
                "comment":"阿姨服务非常好，收拾的很干净。",
                "createtime":1521196598000,
                "nick":"啦啦6666",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/ajNVdqHZLLC5fgciaiaRwm8N48jQG3UahS0Cl34okmQZDcJPGicDYPmoicetPWxPx07clPyFicMEEqYicJkib2LzLEBnQ/0",
                "area":"徐汇区",
                "city":"上海",
                "comment":"准时到达，态度热情，阿姨态度是好的，但是打扫的没有很认真，很多小地方还是挺脏的，阿姨打扫完自己又接着打扫了很久。。",
                "createtime":1521192005000,
                "nick":"阿***",
                "star":3
            },
            {
                "iconUrl":"https://thirdqq.qlogo.cn/qqapp/1103839060/A6F7F782649485AF535B9E4B545127E6/100",
                "area":"浦东新区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521186979000,
                "nick":"yang98792",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/sXkDNHriahEeqD8cicickXHWl0pO1JXcn8YGQuCt5cMCkAia7JSgXnQRxW03bGJ1T8VvYD21LgIVZzPeIkKYDUqpDA/0",
                "area":"杨浦区",
                "city":"上海",
                "comment":"准时到达",
                "createtime":1521182381000,
                "nick":"天之骄子小丽丽",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/11/26/73d69784-4d04-431a-92d9-a8bd21e29518.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521180074000,
                "nick":"邵小笑。",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/GtS5XXtiaCDaXZX34gjkBB3wvEIH8iaH4Queicyw9lOVzgZcxmKqugUyJWgicuPCR9Uicw8ZNdjicSP0nFic2FLDLFreocxHZtlToKO/0",
                "area":"虹口区",
                "city":"上海",
                "comment":"态度热情，服务专业",
                "createtime":1521177079000,
                "nick":"Eli5",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"浦东新区",
                "city":"上海",
                "comment":"服务专业，态度热情，准时到达",
                "createtime":1521175494000,
                "nick":"薛伟明",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"西城区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，阿姨打扫得非常干净整洁 帮了我的大忙 万分感谢",
                "createtime":1521175171000,
                "nick":"清朗的世界",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmGDOd5DxdYdkzK5T66Hp7QMDbE6cC9Spr2rRpmBQibHU58mwiadx6h1CB4yibpVAPxyhicMiblyDeNyg/0",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，值得关注的商家",
                "createtime":1521171938000,
                "nick":"u16046831",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJll76R1TnjSrAZRpJ4OzRDlwYs3VRd6wCDq3miczEqZebHJEqMa9xNnRLA1shJXZaoBDmDUtaMaTg/0",
                "area":"浦东新区",
                "city":"上海",
                "comment":"不太认真 拖时间",
                "createtime":1521171160000,
                "nick":"Ashley徐蕾",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/12/13/f8abe707-61df-4032-99fd-99f1da0a25df.jpg",
                "area":"徐汇区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521118095000,
                "nick":"u29562927",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2017/11/30/9145df02-6c46-4e85-83f6-ccb0c37742f7.jpg",
                "area":"浦东新区",
                "city":"上海",
                "comment":"阿姨态度蛮好，迟到了直说对不起，清洁能力确不咋滴，房间搞了很久，弄到最后客厅马马虎虎的打扫，本来不会评论，但今天意外发现，房间主卧的床下因让她打扫床后给她移动过，地板有磨坏的痕迹，真心郁闷，不得不差评",
                "createtime":1521109205000,
                "nick":"u78690105",
                "star":2
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/oqjmvaMlmyfibgPboLbbdcPVYOE29GPzsJNUYEzLmXXqUgibT6H8TnK3hnialpaqz7zDHnhclKxBXXR6aMic21cbtkTjQdBdmrPd/0",
                "area":"西城区",
                "city":"北京",
                "comment":"服务专业，态度热情，准时到达",
                "createtime":1521107597000,
                "nick":"Hh26",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83erYUwe91zYWvX3BicZoEn41IJBBqSMMZ8csgial5lKA6za1LeTeBnrfXDgfkthPVop0NQu4Qkfoa3icw/132",
                "area":"黄浦区",
                "city":"上海",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521107165000,
                "nick":"〰20",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLmiaNPYbLOk7NBQxdUPDgGaiagxCBDKF26zjibIs2ia1lD2T7cEOzPL8NQBZMCIcDFpus7ia7wSu3vArQ/132",
                "area":"罗湖区",
                "city":"深圳",
                "comment":"嗯呢 服务很好",
                "createtime":1521102876000,
                "nick":"Marco Zambaldo",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/hqDXUD6csUibTwZibQosRbiagoNofUCRXrib28NQribGibyITJ470E2IHnPvkROiaMWCT7lqHryrJnmgMgTqXaqAxzqtw/0",
                "area":"丰台区",
                "city":"北京",
                "comment":"服务太差劲，之前叫了几次保洁阿姨都很好干净，今天这个太差太差，垃圾也不带帮忙带下去",
                "createtime":1521102420000,
                "nick":"u72955327",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/PCyiaLnicfRyDtgeymjP0tovB6ocuGbSens6DoUTHtsRFhjwl19uEWIBDWX9F7MWx6sxldDFMNzcGXktY95glcpw/132",
                "area":"东城区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，很棒",
                "createtime":1521101462000,
                "nick":"呵呵碰",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2018/03/14/2271c471-dea3-437f-a937-00f3a181af42.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1521093966000,
                "nick":"HISA-排骨君",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83ep4NILvBubLqyiaIpHHjeicoTczBk5JcqsngAkMGTtahwnFiaLeR1e8o3asmGNCD7rVzIN5GCzNtUCaA/0",
                "area":"昌平区",
                "city":"北京",
                "comment":"客服很好",
                "createtime":1521093140000,
                "nick":"大菲1",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/DYAIOgq83eqKEnl7B1sLKbVCc0BTNRIZDKkFtwibf8flM2zaE6NfBmMQNy9DeoGjquXibBFcJ71MAckHLeC2m6rQ/0",
                "area":"顺义区",
                "city":"北京",
                "comment":"云家证动不动就取消订单，打乱时间计划",
                "createtime":1521085158000,
                "nick":"静***",
                "star":3
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/ajNVdqHZLLAgfsiavqfFLibxRs6OGYG6d4LpjYcsj3TpCE8TGwUiajbPDkB7WTRCtibBqYnKd8jpwX11aTK6AI9MWg/0",
                "area":"卢湾区",
                "city":"上海",
                "comment":"态度热情，准时到达，服务专业",
                "createtime":1520909483000,
                "nick":"-.-10",
                "star":5
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/Q5xPxqRgZicXHJFFA0cvdyUeuwndkF4khrBazP3EunLpvp2bNGlUwKhLiaYox84Q9B1HIBVLv8xpHRufQ7ibDbfZwCEjHcrdwJq/0",
                "area":"南山区",
                "city":"深圳",
                "comment":"态度热情，服务专业，准时到达",
                "createtime":1520908242000,
                "nick":"王信1",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/PwsCl8vJ2Ubg9GWmTCjlAjxuWMo2hylyUvm0LGPvNhFuu3kI5XXpDNjtFJsqjic00tt1vTneiayESqwBCUr6pp4w/132",
                "area":"罗湖区",
                "city":"深圳",
                "comment":"准时到达，打扫的一般，已经做了心理准备，在预期接受范围内。就是浪费水浪费的太严重了，中国那么多地方缺水，更别提全球了。希望公司和员工提倡下节约用水！！！",
                "createtime":1520860484000,
                "nick":"A***",
                "star":4
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/wIzdjxOSE0b56dc9ibXLPNJOJtZAxncPb3PxaEtj51KtsbxKdvZjePdB2d2XJ1aU9uDSFvOJbN71BbCvveia1Hog/132",
                "area":"朝阳",
                "city":"北京",
                "comment":"话多，还弄得不干净",
                "createtime":1520860281000,
                "nick":"排***",
                "star":3
            },
            {
                "iconUrl":"http://wx.qlogo.cn/mmopen/Q5xPxqRgZicXHJFFA0cvdyUeuwndkF4khrBazP3EunLpvp2bNGlUwKhLiaYox84Q9B1HIBVLv8xpHRufQ7ibDbfZwCEjHcrdwJq/0",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520857879000,
                "nick":"理合",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2016/08/03/8c970507-66c2-4a81-93bc-a32c2746509e.jpg",
                "area":"海淀区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，特别好",
                "createtime":1520851926000,
                "nick":"李丹蕾",
                "star":5
            },
            {
                "iconUrl":"https://wx.qlogo.cn/mmopen/vi_32/uwm9pVB4gDlKibGbRCbN4v2PnnY9guSnJxJaHZ4dicTK5JQMG2EfvLJ0HYgZLrHp7nFLXXNYZCdSEQSbVmGGnSyA/0",
                "area":"荔湾区",
                "city":"广州",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520844348000,
                "nick":"小芝麻2",
                "star":5
            },
            {
                "iconUrl":"https://thirdwx.qlogo.cn/mmopen/vi_32/z7Nba05uObuZ10tmT2gksxWR7zMeBERBo3HAjtnwGQV8X6mcc9w2ibXy4Jgs3Vjh7m3sAibAHxicHlghhJjiaOXftw/132",
                "area":"南山区",
                "city":"深圳",
                "comment":"准时到达，服务专业，态度热情",
                "createtime":1520837432000,
                "nick":"理合",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2016/09/10/9b720bbd-b001-453d-b73b-86d6fb187d7d.jpg",
                "area":"武侯区",
                "city":"成都",
                "comment":"态度热情",
                "createtime":1520831084000,
                "nick":"唐wl",
                "star":5
            },
            {
                "iconUrl":"http://img.daoway.cn/img/2018/03/11/3c159dc9-c4ec-40d7-9144-9fc90f480a16.jpg",
                "area":"朝阳区",
                "city":"北京",
                "comment":"准时到达，服务专业，态度热情，很好的",
                "createtime":1520830596000,
                "nick":"u16046831",
                "star":5
            }
        ],function(){});
        City.create([{"name":"北京"},{"name":"上海"},{"name":"广州"},{"name":"深圳"},{"name":"成都"},{"name":"天津"},{"name":"南京"},{"name":"杭州"},{"name":"重庆"},{"name":"苏州"},{"name":"武汉"},{"name":"长沙"},{"name":"济南"},{"name":"郑州"},{"name":"西安"},{"name":"沈阳"},{"name":"福州"},{"name":"厦门"},{"name":"南昌"},{"name":"合肥"},{"name":"宁波"},{"name":"无锡"},{"name":"青岛"},{"name":"大连"},{"name":"东莞"},{"name":"佛山"},{"name":"石家庄"},{"name":"哈尔滨"},{"name":"太原"},{"name":"昆明"},{"name":"贵阳"},{"name":"南宁"},{"name":"温州"}],function(){})
    }
});
router.get('/getItem',function(req,res,next){
    Item.find({},function(err,docs){
        res.json(docs)
    });
});
router.get('/getShop',function(req,res,next){
    Shop.find({},function(err,docs){
        if(!err){
            res.json(docs);
        }
    });
});
router.get('/getService',function(req,res,next){
    Service.find({},function(err,docs){
        console.log('service',docs.length);
        res.json(docs)
    });
});
router.get('/getComment',function(req,res,next){
    console.log('page参数：'+req.query.page)
    const page = req.query.page || 1;
    const projection = null;
    const _filter = {
        limit:10,
        sort:'-createtime',
        //默认升序，用降序
        skip:(page-1)*10,
    };
    Comment.find({},projection,_filter,function(err,docs){
        console.log(docs)
        res.json(docs)
    });
});
router.get('/getCity',function(req,res,next){
    City.find({},function(err,docs){
        if(!err){
            res.json(docs);
        }
    })
});
module.exports = router;
